# Generated by Django 3.2.9 on 2022-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_alter_sparrowadminacademicsettingmodel_default_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladminacademicsettingmodel',
            name='term',
            field=models.CharField(choices=[('1st TERM', '1st TERM'), ('2nd TERM', '2nd TERM'), ('3rd TERM', '3rd TERM')], max_length=10),
        ),
    ]
