# Generated by Django 4.0.1 on 2022-01-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_admin', '0004_delete_schoolmodel'),
        ('setting', '0005_alter_schooladminacademicsettingmodel_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdminResultSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2)),
                ('assignments', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparrow_admin.schoolsmodel')),
            ],
        ),
    ]
