# Generated by Django 3.2.9 on 2022-01-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('site_info_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_line_one', models.CharField(blank=True, max_length=20, null=True)),
                ('site_line_two', models.CharField(blank=True, max_length=20, null=True)),
                ('site_social_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('site_social_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('site_social_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('site_social_linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('site_address', models.TextField()),
                ('site_image', models.FileField(blank=True, null=True, upload_to='images/site_images')),
            ],
        ),
    ]
