# Generated by Django 3.2.9 on 2022-01-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220106_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteinfomodel',
            old_name='site_social_youtube_video',
            new_name='site_social_youtube_video_link',
        ),
    ]
