# Generated by Django 3.2.9 on 2021-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_admin', '0002_alter_schoolsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsmodel',
            name='applicant_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolsmodel',
            name='line_one',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolsmodel',
            name='line_two',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
