# Generated by Django 3.2.9 on 2021-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MISS', 'MISS'), ('MS', 'MS'), ('DOC', 'DOC'), ('BARR', 'BARR'), ('PST', 'PST'), ('PROF', 'PROF'), ('ENGR', 'ENGR')], max_length=10)),
                ('surname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/parent_images')),
                ('residential_address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('office_address', models.CharField(blank=True, max_length=200, null=True)),
                ('office_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('c', 'CHRISTIANITY'), ('i', 'ISLAM'), ('o', 'OTHERS')], max_length=3)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(blank=True, choices=[('', ''), ('ab', 'ABIA'), ('an', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True)),
                ('lga', models.CharField(blank=True, choices=[('', ''), ('ab', 'ABIA'), ('an', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
