# Generated by Django 3.2.9 on 2021-12-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20211219_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmodel',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.staffmodel'),
        ),
    ]
