# Generated by Django 3.2.9 on 2021-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_staffmodel_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='lga',
            field=models.CharField(blank=True, choices=[('ab', 'ABIA'), ('an', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='position',
            field=models.CharField(choices=[('pri', 'Principal'), ('vpa', 'Vice Principal Admin'), ('tea', 'Teacher')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='religion',
            field=models.CharField(choices=[('c', 'CHRISTIANITY'), ('i', 'ISLAM'), ('o', 'OTHERS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='section',
            field=models.CharField(choices=[('a', 'Academic'), ('n', 'Non Academic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='state_of_origin',
            field=models.CharField(blank=True, choices=[('ab', 'ABIA'), ('an', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='lga',
            field=models.CharField(blank=True, choices=[('ab', 'ABIA'), ('an', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='nationality',
            field=models.CharField(default='Nigerian', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='religion',
            field=models.CharField(choices=[('c', 'CHRISTIANITY'), ('i', 'ISLAM'), ('o', 'OTHERS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='state_of_origin',
            field=models.CharField(blank=True, choices=[('ab', 'ABIA'), ('an', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True),
        ),
    ]
