# Generated by Django 3.2.9 on 2021-12-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20211229_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='relationship_with_student',
            field=models.CharField(choices=[('father', 'FATHER'), ('mother', 'MOTHER')], default='father', max_length=20),
            preserve_default=False,
        ),
    ]
