# Generated by Django 3.2.9 on 2022-01-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_admin', '0003_auto_20211218_1143'),
        ('registration', '0013_auto_20211229_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sparrow_admin.schoolsmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='religion',
            field=models.CharField(blank=True, choices=[('c', 'CHRISTIANITY'), ('i', 'ISLAM'), ('o', 'OTHERS')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='residential_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/student_images'),
        ),
    ]
