# Generated by Django 3.2.9 on 2022-01-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20220101_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsmodel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentsmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parentsmodel',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentsmodel',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIANITY', 'CHRISTIANITY'), ('ISLAM', 'ISLAM'), ('OTHERS', 'OTHERS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parentsmodel',
            name='residential_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='position',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal Admin', 'Vice Principal Admin'), ('Teacher', 'Teacher')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='state_of_origin',
            field=models.CharField(blank=True, choices=[('ab', 'ABIA'), ('ANAMBRA', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True),
        ),
    ]
