# Generated by Django 3.2.9 on 2022-01-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20220102_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmodel',
            name='parents',
        ),
        migrations.AddField(
            model_name='studentsmodel',
            name='parents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.parentsmodel'),
            preserve_default=False,
        ),
    ]
