# Generated by Django 3.2.9 on 2022-01-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20220102_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsmodel',
            old_name='parents',
            new_name='parent',
        ),
    ]
