# Generated by Django 3.2.9 on 2022-01-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_rename_parents_studentsmodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='position',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
