# Generated by Django 3.2.9 on 2022-01-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_staffmodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='position',
            field=models.CharField(choices=[('', '----------'), ('TEACHER', 'TEACHER'), ('LAB ATTENDANT', 'LAB ATTENDANT'), ('PSYCHOLOGIST', 'PSYCHOLOGIST'), ('NANNY', 'NANNY'), ('PRINCIPAL', 'PRINCIPAL'), ('VICE PRINCIPAL ACADEMIC', 'VICE PRINCIPAL ACADEMIC'), ('VICE PRINCIPAL ADMINISTRATION', 'VICE PRINCIPAL ADMINISTRATION'), ('DIRECTOR', 'DIRECTOR'), ('PROPRIETOR', 'PROPRIETOR'), ('ACCOUNTANT', 'ACCOUNTANT'), ('BURSARY', 'BURSARY'), ('REGISTRAR', 'REGISTRAR'), ('RECEPTIONIST', 'RECEPTIONIST'), ('ICT', 'ICT'), ('CHIEF SECURITY OFFICER', 'CHIEF SECURITY OFFICER'), ('SECURITY OFFICER', 'SECURITY OFFICER'), ('CHEF', 'CHEF'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIANITY', 'CHRISTIANITY'), ('ISLAM', 'ISLAM'), ('OTHERS', 'OTHERS')], max_length=20, null=True),
        ),
    ]
