# Generated by Django 3.2.9 on 2022-01-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_studentsmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='relationship_with_parent',
            field=models.CharField(choices=[('father', 'FATHER'), ('mother', 'MOTHER'), ('sister', 'SISTER'), ('brother', 'BROTHER'), ('uncle', 'UNCLE'), ('aunty', 'AUNTY'), ('pastor', 'PASTOR'), ('others', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIANITY', 'CHRISTIANITY'), ('ISLAM', 'ISLAM'), ('OTHERS', 'OTHERS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.classesmodel'),
        ),
    ]
