# Generated by Django 3.2.9 on 2021-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_staffmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='position',
            field=models.CharField(choices=[('', ''), ('', '')], default='l', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='section',
            field=models.CharField(choices=[('a', 'Academic'), ('n', 'Non Academic')], default='l', max_length=20),
            preserve_default=False,
        ),
    ]
