# Generated by Django 3.2.9 on 2021-12-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20211229_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsmodel',
            name='relationship_with_student',
        ),
        migrations.AddField(
            model_name='studentsmodel',
            name='relationship_with_parent',
            field=models.CharField(choices=[('father', 'FATHER'), ('mother', 'MOTHER')], default='father', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentsmodel',
            name='lga',
            field=models.CharField(blank=True, choices=[('ab', 'ABIA'), ('an', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentsmodel',
            name='religion',
            field=models.CharField(choices=[('c', 'CHRISTIANITY'), ('i', 'ISLAM'), ('o', 'OTHERS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='parentsmodel',
            name='state_of_origin',
            field=models.CharField(blank=True, choices=[('ab', 'ABIA'), ('an', 'ANAMBRA'), ('be', 'BENUE'), ('cr', 'CROSS RIVER')], max_length=50, null=True),
        ),
    ]
