# Generated by Django 3.2.9 on 2022-01-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dash_format', models.CharField(max_length=20)),
                ('slash_format', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SparrowAdminAcademicSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_term', models.CharField(choices=[(1, '1st TERM'), (2, '2nd TERM'), (3, '3rd TERM')], max_length=1)),
                ('default_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.sessionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAdminAcademicSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[(1, '1st TERM'), (2, '2nd TERM'), (3, '3rd TERM')], max_length=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.sessionmodel')),
            ],
        ),
    ]
