# Generated by Django 3.2.9 on 2022-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='status',
            field=models.CharField(choices=[('a', 'ACTIVE'), ('p', 'PAST'), ('f', 'NEXT')], default='f', max_length=1),
            preserve_default=False,
        ),
    ]
