# Generated by Django 3.2.9 on 2022-01-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_admin', '0004_delete_schoolmodel'),
        ('setting', '0002_sessionmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladminacademicsettingmodel',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sparrow_admin.schoolsmodel'),
            preserve_default=False,
        ),
    ]
