# Generated by Django 3.2.9 on 2022-01-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_admin', '0003_auto_20211218_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolModel',
        ),
    ]
